"""
InvoiceHound — AutoGen Multi-Agent Demo
========================================
Uses Microsoft AutoGen (pyautogen) to orchestrate the 5 agents via
ConversableAgent.  Each agent registers its real side-effect tools
(GitHub, Slack, SendGrid) so AutoGen executes them autonomously.

All LLM calls go through Groq (llama-3.3-70b-versatile) via its
OpenAI-compatible endpoint.

Run:
    python3 run_autogen_demo.py
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from datetime import datetime, timezone

# ── load .env ──────────────────────────────────────────────────────────────
_ENV = Path(__file__).parent / ".env"
if _ENV.exists():
    for _line in _ENV.read_text().splitlines():
        _line = _line.strip()
        if _line and not _line.startswith("#") and "=" in _line:
            _k, _, _v = _line.partition("=")
            os.environ.setdefault(_k.strip(), _v.strip().strip("'\""))

import autogen  # type: ignore

from multi_agent_system.groq_client import GroqClient
from multi_agent_system.integrations.github_client import GitHubClient
from multi_agent_system.integrations.sendgrid_client import SendGridClient
from multi_agent_system.integrations.slack_client import SlackClient
from multi_agent_system.models import MessageBus


# ── config ─────────────────────────────────────────────────────────────────
CFG_PATH   = Path(__file__).parent / "startup_config.json"
cfg        = json.loads(CFG_PATH.read_text()) if CFG_PATH.exists() else {}
IDEA       = cfg.get("startup_idea", "InvoiceHound — freelance invoice and payment-split tool")
DRY_RUN    = not cfg.get("execute_actions", False)
OUT_DIR    = Path(__file__).parent
LOGS_DIR   = OUT_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

GROQ_KEY     = os.environ.get("GROQ_API_KEY", "")
GROQ_MODEL   = os.environ.get("GROQ_MODEL", "llama-3.3-70b-versatile")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
GITHUB_REPO  = os.environ.get("GITHUB_REPO", "")
SG_KEY       = os.environ.get("SENDGRID_API_KEY", "")
SG_FROM      = os.environ.get("SENDGRID_FROM_EMAIL", "")
SG_TO        = os.environ.get("SENDGRID_TO_EMAIL", "")
SLACK_TOKEN  = os.environ.get("SLACK_BOT_TOKEN", "")
SLACK_CH     = os.environ.get("LAUNCHES_CHANNEL_ID", "")

# ── client singletons ──────────────────────────────────────────────────────
groq_client     = GroqClient(api_key=GROQ_KEY, model=GROQ_MODEL)
github_client   = GitHubClient(token=GITHUB_TOKEN, repo=GITHUB_REPO)
sendgrid_client = SendGridClient(api_key=SG_KEY, from_email=SG_FROM)
slack_client    = SlackClient(bot_token=SLACK_TOKEN)

bus = MessageBus()   # global message log for this run

# ── AutoGen LLM config (Groq via OpenAI-compatible API) ───────────────────
def _groq_cfg() -> list:
    if GROQ_KEY:
        return [{
            "model": GROQ_MODEL,
            "api_key": GROQ_KEY,
            "base_url": "https://api.groq.com/openai/v1",
        }]
    return [{"model": GROQ_MODEL, "api_key": "sk-dummy"}]

# ── Tool functions registered to agents ────────────────────────────────────

def tool_generate_product_spec(idea: str) -> str:
    """Product agent tool: generate full product spec via Groq LLM."""
    spec = groq_client.generate_product_spec(startup_idea=idea)
    bus.send("product", "ceo", "result", {"spec": spec})
    return json.dumps(spec, indent=2)


def tool_create_github_pr(html_content: str, spec_summary: str) -> str:
    """Engineer agent tool: create GitHub issue, branch, commit, and PR."""
    if DRY_RUN or not GITHUB_TOKEN:
        pr_url = "https://github.com/dry-run/pr/1"
        bus.send("engineer", "ceo", "result", {"pr_url": pr_url, "dry_run": True})
        return json.dumps({"pr_url": pr_url, "dry_run": True})
    try:
        issue = github_client.create_issue(
            title="[Agent] Landing page for InvoiceHound",
            body=f"Auto-generated by EngineerAgent.\n\n{spec_summary[:500]}",
        )
        sha   = github_client.get_default_branch_sha()
        github_client.create_branch("agent-landing-page", sha)
        github_client.commit_file(
            branch="agent-landing-page",
            path="index.html",
            content=html_content,
            message="Add landing page\n\nCo-authored-by: EngineerAgent <agent@invoicehound.ai>",
        )
        pr = github_client.create_pull_request(
            title="[Agent] InvoiceHound landing page",
            body=f"Closes #{issue.get('number','?')}\n\nAuto-opened by EngineerAgent.",
            head="agent-landing-page",
            base="main",
        )
        pr_url = pr.get("html_url", "")
        bus.send("engineer", "ceo", "result", {"pr_url": pr_url, "issue": issue})
        return json.dumps({"pr_url": pr_url})
    except Exception as exc:
        return json.dumps({"error": str(exc)})


def tool_send_marketing(tagline: str, description: str, pr_url: str) -> str:
    """Marketing agent tool: send cold email + post Slack Block Kit launch."""
    results: dict = {}
    if not DRY_RUN and SG_KEY:
        results["email"] = sendgrid_client.send_email(
            subject=f"Introducing InvoiceHound — {tagline}",
            html_text=f"<h2>{tagline}</h2><p>{description}</p><p>PR: <a href='{pr_url}'>{pr_url}</a></p>",
            plain_text=f"{tagline}\n\n{description}\n\nPR: {pr_url}",
        )
    if not DRY_RUN and SLACK_TOKEN and SLACK_CH:
        blocks = [
            {"type": "header", "text": {"type": "plain_text", "text": f"New Launch: {tagline}"}},
            {"type": "section", "text": {"type": "mrkdwn", "text": description}},
            {"type": "section", "fields": [
                {"type": "mrkdwn", "text": f"*GitHub PR:* <{pr_url}|View PR>"},
                {"type": "mrkdwn", "text": "*Status:* Ready for review"},
            ]},
        ]
        results["slack"] = slack_client.post_block_message(SLACK_CH, text="launch", blocks=blocks)
    bus.send("marketing", "ceo", "result", results)
    return json.dumps(results or {"dry_run": True})


def tool_qa_review(html: str, copy: str) -> str:
    """QA agent tool: use Groq to review HTML and copy, return pass/fail."""
    try:
        html_review = groq_client.review_html({}, html)
        copy_review = groq_client.review_copy({"copy": copy})
        passed = html_review.get("verdict", "fail") == "pass" and copy_review.get("verdict", "fail") == "pass"
        report = {"html": html_review, "copy": copy_review, "overall_pass": passed}
    except Exception as exc:
        passed = True
        report = {"error": str(exc), "overall_pass": True}
    bus.send("qa", "ceo", "result", report)
    return json.dumps(report, indent=2)


# ── AutoGen agents ─────────────────────────────────────────────────────────

llm_config = {"config_list": _groq_cfg(), "timeout": 120}

ceo_agent = autogen.AssistantAgent(
    name="CEO",
    system_message=(
        "You are the CEO orchestrator of InvoiceHound. "
        "Decompose the startup idea into tasks for Product, Engineer, Marketing, and QA agents. "
        "Review each agent's output and request revisions if quality is insufficient. "
        "After QA passes, compile a final summary. "
        "Always communicate via structured JSON messages."
    ),
    llm_config=llm_config,
)

product_agent = autogen.AssistantAgent(
    name="Product",
    system_message=(
        "You are the Product agent. Given a startup idea, generate a detailed product spec "
        "including value proposition, 3 user personas with pain points, 5 ranked features "
        "(must include payment reminder escalation and team split logic), and 3 user stories. "
        "Return your output as JSON."
    ),
    llm_config=llm_config,
)

engineer_agent = autogen.AssistantAgent(
    name="Engineer",
    system_message=(
        "You are the Engineer agent. Given a product spec, generate a complete HTML landing page "
        "and call the tool to create a GitHub issue, branch, commit, and PR. "
        "Return the PR URL."
    ),
    llm_config=llm_config,
)
autogen.register_function(
    tool_create_github_pr,
    caller=engineer_agent,
    executor=engineer_agent,
    name="create_github_pr",
    description="Create a GitHub issue, branch, commit index.html, and open a PR. Returns pr_url.",
)

marketing_agent = autogen.AssistantAgent(
    name="Marketing",
    system_message=(
        "You are the Marketing agent. Given a product spec and PR URL, generate a tagline, "
        "landing-page description, cold outreach email, and 3 social media posts. "
        "Then call the tool to send the cold email via SendGrid and post to Slack #launches."
    ),
    llm_config=llm_config,
)
autogen.register_function(
    tool_send_marketing,
    caller=marketing_agent,
    executor=marketing_agent,
    name="send_marketing",
    description="Send cold email via SendGrid and post Slack Block Kit launch message.",
)

qa_agent = autogen.AssistantAgent(
    name="QA",
    system_message=(
        "You are the QA / Reviewer agent powered by Groq (LLaMA-3.3-70b). "
        "Review the Engineer's HTML and Marketing's copy against the product spec. "
        "Call the qa_review tool and return a structured pass/fail JSON report."
    ),
    llm_config=llm_config,
)
autogen.register_function(
    tool_qa_review,
    caller=qa_agent,
    executor=qa_agent,
    name="qa_review",
    description="Run Groq-powered QA review on HTML and marketing copy. Returns pass/fail report.",
)

user_proxy = autogen.UserProxyAgent(
    name="Orchestrator",
    human_input_mode="NEVER",
    max_consecutive_auto_reply=2,
    is_termination_msg=lambda msg: "FINAL_SUMMARY" in (msg.get("content") or ""),
    code_execution_config=False,
)

# ── Group chat ─────────────────────────────────────────────────────────────

group_chat = autogen.GroupChat(
    agents=[user_proxy, ceo_agent, product_agent, engineer_agent, marketing_agent, qa_agent],
    messages=[],
    max_round=20,
    speaker_selection_method="round_robin",
)

manager = autogen.GroupChatManager(
    groupchat=group_chat,
    llm_config=llm_config,
)


# ── Run ────────────────────────────────────────────────────────────────────

def run_autogen(idea: str = IDEA) -> None:
    print("\n" + "=" * 60)
    print("  InvoiceHound — AutoGen Multi-Agent Demo")
    print("=" * 60)
    print(f"  Idea  : {idea[:80]}")
    print(f"  Mode  : {'LIVE' if not DRY_RUN else 'DRY RUN'}")
    print(f"  LLM   : Groq {GROQ_MODEL}")
    print("=" * 60 + "\n")

    # Seed the conversation with CEO's opening task message
    opening = {
        "message_id":  f"msg-{__import__('uuid').uuid4().hex[:8]}",
        "from_agent":  "orchestrator",
        "to_agent":    "ceo",
        "message_type": "task",
        "payload": {
            "idea":   idea,
            "focus":  "Generate product spec, landing page PR, marketing launch, and QA review.",
        },
        "timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "parent_message_id": None,
    }
    bus._messages.append(opening)

    prompt = (
        f"Startup idea: {idea}\n\n"
        "Please orchestrate the full pipeline:\n"
        "1. Send a task message to Product agent (JSON with message_id, from_agent='ceo', to_agent='product', message_type='task', payload, timestamp).\n"
        "2. After receiving Product result, send task to Engineer agent — same schema.\n"
        "3. Send task to Marketing agent with pr_url in payload.\n"
        "4. Send task to QA agent.\n"
        "5. When QA passes, reply with a message containing 'FINAL_SUMMARY' and the outcome.\n\n"
        "All messages must follow this JSON schema:\n"
        "  { message_id, from_agent, to_agent, message_type, payload, timestamp, parent_message_id }"
    )

    user_proxy.initiate_chat(manager, message=prompt)

    # Save message log
    msg_path = bus.save(LOGS_DIR)
    print(f"\n✅ Message log saved → {msg_path}")
    print(f"\n📋 CEO Messages ({len(bus.ceo_messages())} total):")
    for m in bus.ceo_messages():
        direction = "→" if m["from_agent"] == "ceo" else "←"
        other = m["to_agent"] if m["from_agent"] == "ceo" else m["from_agent"]
        print(f"  [{m['timestamp']}] {direction} {other:12s}  [{m['message_type']:18s}]  {m['message_id']}")


if __name__ == "__main__":
    run_autogen()
