"""Engineer agent with real GitHub actions (Groq-only LLM generation)."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict

from multi_agent_system.groq_client import GroqClient
from multi_agent_system.integrations.github_client import GitHubClient
from multi_agent_system.models import AgentResult, TaskMessage


class EngineerAgent:
    agent_name = "engineer"

    def __init__(self, groq_client: GroqClient, github_client: GitHubClient, dry_run: bool = True) -> None:
        self.groq = groq_client
        self.github_client = github_client
        self.dry_run = dry_run

    def run(self, task: TaskMessage, revision_instruction: str = "") -> AgentResult:
        product_spec = task.context.get("product_spec", {})
        assets = self.groq.generate_engineer_assets(
            startup_idea=task.startup_idea,
            product_spec=product_spec,
            revision_instruction=revision_instruction,
        ) if self.groq.enabled else {
            "html": "<!doctype html><html><body><h1>InvoiceHound</h1></body></html>",
            "issue_title": "Build InvoiceHound landing page",
            "issue_body": "Initial landing page for InvoiceHound.",
            "pr_title": "Initial landing page",
            "pr_body": "Adds initial landing page.",
        }
        html = str(assets.get("html", ""))

        # Pull hero copy from generated HTML when present so UI matches the iframe
        headline = "InvoiceHound"
        subheadline = "Freelance invoicing and payment reminders."
        cta = "Get started"
        try:
            import re
            m = re.search(r"<h1[^>]*>(.*?)</h1>", html, re.I | re.DOTALL)
            if m:
                headline = re.sub(r"<[^>]+>", " ", m.group(1)).replace("\n", " ").strip()[:200]
            m2 = re.search(
                r"class=\"hero\"[^>]*>.*?<p[^>]*>(.*?)</p>",
                html,
                re.I | re.DOTALL,
            )
            if m2:
                subheadline = re.sub(r"<[^>]+>", " ", m2.group(1)).replace("\n", " ").strip()[:240]
            m3 = re.search(r"class=\"hero-cta\"[^>]*>(.*?)</a>", html, re.I | re.DOTALL)
            if m3:
                cta = re.sub(r"<[^>]+>", " ", m3.group(1)).strip()[:120]
        except Exception:
            pass

        output: Dict[str, Any] = {
            "headline": headline,
            "subheadline": subheadline,
            "cta": cta,
            "html": html,
            "issue_url": "",
            "pr_url": "",
            "branch": "agent-landing-page",
            "repo": self.github_client.repo,
        }
        if self.dry_run:
            output["issue_url"] = "dry-run://issue"
            output["pr_url"] = "dry-run://pr"
            return AgentResult(agent_name=self.agent_name, task_id=task.task_id, output=output)

        # Assignment requirement: open PR against main.
        # (If a repo uses a different default branch, update the assignment repo accordingly.)
        base_branch = "main"

        # Assignment requirement: issue title must be exactly this.
        issue_title = "Initial landing page"
        issue_body = str(assets.get("issue_body", "")) or f"Startup idea:\n{task.startup_idea}"
        issue = self.github_client.create_issue(issue_title, issue_body)
        output["issue_url"] = str(issue.get("html_url", ""))

        try:
            self.github_client.create_branch("agent-landing-page", base_branch)
        except Exception:
            # Branch may already exist in repeated runs.
            pass

        self.github_client.upsert_file(
            branch="agent-landing-page",
            path="index.html",
            content_text=html,
            message="Add InvoiceHound landing page generated by Engineer Agent",
        )

        pr_title = str(assets.get("pr_title", "Initial landing page"))
        pr_body = str(assets.get("pr_body", "Adds initial landing page."))
        try:
            pr = self.github_client.create_pr(
                title=pr_title,
                body=pr_body,
                head="agent-landing-page",
                base=base_branch,
            )
        except Exception:
            # Common GitHub 422 causes:
            # - PR already exists for the same head/base
            # - No commits between base and head
            # In both cases, handle gracefully for demos.
            existing = self.github_client.list_open_prs(head="agent-landing-page", base=base_branch)
            if existing:
                pr = existing[0]
            else:
                # Force a tiny change so there is definitely a diff
                stamp2 = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
                html2 = html + f"\n<!-- build: {stamp2} -->\n"
                self.github_client.upsert_file(
                    branch="agent-landing-page",
                    path="index.html",
                    content_text=html2,
                    message=f"Update landing page build stamp {stamp2}",
                )
                pr = self.github_client.create_pr(
                    title=pr_title,
                    body=pr_body,
                    head="agent-landing-page",
                    base=base_branch,
                )
        output["pr_url"] = str(pr.get("html_url", ""))
        output["pr_number"] = pr.get("number")
        output["base_branch"] = base_branch
        return AgentResult(agent_name=self.agent_name, task_id=task.task_id, output=output)

