"""Engineer agent with real GitHub actions."""

from typing import Any, Dict

from multi_agent_system.agents.base import BaseAgent
from multi_agent_system.integrations.github_client import GitHubClient
from multi_agent_system.models import AgentResult, TaskMessage


class EngineerAgent(BaseAgent):
    agent_name = "engineer"

    def __init__(self, llm, github_client: GitHubClient, dry_run: bool = True) -> None:
        super().__init__(llm)
        self.github_client = github_client
        self.dry_run = dry_run

    def build_system_prompt(self) -> str:
        return "You are an engineer building a polished startup landing page. Return JSON."

    def build_output_contract(self) -> str:
        return "Return JSON with html only."

    def run(self, task: TaskMessage, revision_instruction: str = "") -> AgentResult:
        product_spec = task.context.get("product_spec", {})
        html = self.llm.generate_landing_page_html(task.startup_idea, product_spec)

        output: Dict[str, Any] = {
            "headline": "Your team did the work. We make sure you get paid.",
            "subheadline": "One invoice to the client. Automatic reminders. Fair splits. Zero awkward conversations.",
            "cta": "Start Chasing Invoices Free",
            "html": html,
            "issue_url": "",
            "pr_url": "",
            "branch": "agent-landing-page",
            "repo": self.github_client.repo,
        }
        if self.dry_run:
            output["issue_url"] = "dry-run://issue"
            output["pr_url"] = "dry-run://pr"
            return AgentResult(agent_name=self.agent_name, task_id=task.task_id, output=output)

        repo_data = self.github_client.get_repo()
        base_branch = str(repo_data.get("default_branch", "main"))

        issue_body = (
            "Create the initial InvoiceHound landing page with headline, subheadline, "
            "five feature cards, 3-step flow, and CTA.\n\n"
            f"Startup idea:\n{task.startup_idea}"
        )
        issue = self.github_client.create_issue("Initial landing page for InvoiceHound", issue_body)
        output["issue_url"] = str(issue.get("html_url", ""))

        try:
            self.github_client.create_branch("agent-landing-page", base_branch)
        except Exception:
            # Branch may already exist in repeated runs.
            pass

        self.github_client.upsert_file(
            branch="agent-landing-page",
            path="index.html",
            content_text=html,
            message="Add InvoiceHound landing page generated by Engineer Agent",
        )

        pr_title = "InvoiceHound: add initial landing page"
        pr_body = (
            "## Summary\n"
            "- Adds an initial InvoiceHound landing page (`index.html`).\n"
            "- Includes headline/subheadline, 5 feature cards, and 3-step flow.\n"
            "- Adds CTA: Start Chasing Invoices Free.\n\n"
            "## Why\n"
            "Supports the MVP launch narrative for freelancers who need automated invoice reminders."
        )
        pr = self.github_client.create_pr(
            title=pr_title,
            body=pr_body,
            head="agent-landing-page",
            base=base_branch,
        )
        output["pr_url"] = str(pr.get("html_url", ""))
        output["pr_number"] = pr.get("number")
        output["base_branch"] = base_branch
        return AgentResult(agent_name=self.agent_name, task_id=task.task_id, output=output)

